/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guice.spark.graphql;

import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;

public class App {
    @Inject
    private HelloWorldService service;//hello service

    public static void main(String[] args) {
        App app = new App();

        Injector injector = Guice.createInjector(new HelloWorldModule());
        injector.injectMembers(app);

        app.testGuice();
    }


    public void testGuice()
    {
        service.sayHello();//usage of the service
    }
}
